name: Invictus
markdown: redcarpet
pygments: true

baseurl: /Invictus
url: http://tommsy64.github.io/Invictus
repository: https://github.com/Tommsy64/Invictus


gems: 
- jekyll-mentions 
- jemoji 
- jekyll-redirect-from

kramdown: 
  input: GFM

redcarpet:
  extensions: [strikethrough, tables]