highlighter: pygments
name: Invictus
markdown: redcarpet
pygments: true
repository: https://github.com/Tommsy64/Invictus
gems: 
- jekyll-mentions 
- jemoji 
- jekyll-redirect-from
kramdown: 
  input: GFM
baseurl: /Invictus